@startuml

participant ":Game" as gm
participant "currentlyActive:Scene" as sc
participant "theGameObjectName:GameObject" as go

-> gm : selectObject(theGameObjectName)
activate gm
gm -> sc :getObjectOptions(theGameObjectName)
activate sc
sc -> go :getObjectOptions(theGameObjectName)
activate go
go --> sc :return:ObjectOptions(list:Interactions)
deactivate go
sc --> gm :return:ObjectOptions(list:Interactions)
deactivate sc
<-- gm :return:ObjectOptions(list:Interactions)

@enduml