@startuml

participant ":Game" as gm
participant "currentlyActive:Scene" as sc
participant ":GameObjectRepository" as ga
participant "theGameObjectName:GameObject" as go


-> gm : initiateSelect(theGameObjectName)
activate gm
gm -> sc :isAvailable(gameElementName)
activate sc
sc -> gm : return: Bool
deactivate sc
gm -> ga :getGameObject(gameElementName)
activate ga
ga --> gm : return:gameObject
deactivate ga
gm -> go : listInteractionTypes()
activate go
go --> gm : return: list:theInteraction
deactivate go
<-- gm : return: list:theInteraction
deactivate gm

@enduml