@startuml

participant ":Game" as gm
participant ":Memo" as me
participant "theGameObjectName:GameObject" as go
participant "Interactiontype:" as in


-> gm : selectInteraction(theInteractiontype)
gm -> me : selectInteraction(theInteractiontype)
me -> go : selectGameObject(AktivObject,InteactionType)
go -> in : getInteractionOption(InteractionType)
in -> me : return(interactioption)
in ->  : return(interactioption)

@enduml
