@startuml

participant ":Game" as gm
participant "currentlyActive:Scene" as sc
participant "theGameObjectName:GameObject" as go

-> gm : initiateSelect(theGameObjectName)
activate gm
gm -> sc :selectGameObject(theGameObjectName)
activate sc
sc -> go :getObject(theGameObjectName)
activate go
go --> sc :return:GameObject(theGameObjectName)
deactivate go

@enduml