@startuml

participant ":Game" as gm
participant "interactionType:Option" as op



-> gm : setInteractionOptions(theOptions)
activate gm
gm -> op : setOptions(theOptions)
activate op
op --> gm : return comfirm option
deactivate op
<-- gm : return comfirm option
deactivate gm
@enduml
